version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.0
    - 5.21.1
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.0
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.29.0
    - 5.30.0
    - 5.31.0
    - 5.31.1
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
  - dependency-name: "@wdio/sync"
    versions:
    - 6.11.0
    - 7.0.0
    - 7.0.1
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.5
    - 7.0.7
    - 7.0.8
    - 7.0.9
    - 7.1.0
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.2.2
    - 7.2.3
    - 7.3.0
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 7.4.5
    - 7.5.0
    - 7.5.1
  - dependency-name: "@wdio/mocha-framework"
    versions:
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.1.1
    - 7.1.2
    - 7.2.0
    - 7.2.1
    - 7.3.0
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 7.4.6
  - dependency-name: webdriver
    versions:
    - 6.12.1
    - 7.0.0
    - 7.0.2
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.1.1
    - 7.2.0
    - 7.2.1
    - 7.3.0
    - 7.3.1
    - 7.4.0
    - 7.4.1
    - 7.4.2
    - 7.5.0
  - dependency-name: css-loader
    versions:
    - 5.2.3
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 11.0.0
    - 12.0.0
    - 12.0.1
    - 12.1.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
  - dependency-name: typescript
    versions:
    - 4.1.5
  - dependency-name: "@babel/preset-typescript"
    versions:
    - 7.12.13
